name: hm-img
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/15 * * * *'
env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  hm_job:
    if: always()
    uses: ./.github/workflows/reusable-hm.yml
    with:
      marka: hm
    secrets: inherit
