name: hm-img
on:
  schedule:
    - cron:  '0 3 * * 1,3'
env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  hm_job:
    if: always()
    uses: ./.github/workflows/reusable-hm.yml
    with:
      marka: hm
    secrets: inherit
